title: "Home of Liam&nbsp;Z."
tagline: Learner,&nbsp;hacker,&nbsp;thinker.
description: "Home of Liam Z. â€” learner, hacker, thinker."

menu:
  - text: About&nbsp;me
    url:  /about/
  - text: Endeavours
    url:  /endeavours/
  - text: Contact
    url:  /contact/
  - text: Quotes
    url:  /quotes/

# Server
hostname: "liamz.co"

exclude: 
- README.md
- rakefile
- TODO

# Misc.
markdown: maruku
# We still need this line below, for _plugins/permalink.rb
permalink: pretty
timezone: 'Australia/Brisbane'

# Overridden in _plugins/ext.rb for `jekyll build`
asset_pipeline:
  bundle: false
  compress: false
